### ISSUE TITLE
操作説明とか投稿用の文章を作る

### ISSUE THREAD

**Issue by Zaslon** [ld44-team-mukade/ld44-maingame#103]

**Comment by tanitta** [comment]
前回のやつです

![title.png](///content/b19/6/z/c8dc.png)

![ss](///content/b19/6/z/c910.png)

## Description

I did it! 

I got seeds of millionaire!
My bro said me only I should do is clickin'.
Make it rain!



邪魔するな！

やったぜ！億万長者の種を手に入れた！
俺のダチはただクリックすれば良いって言ってたな．
金の雨降らせてやるぜ！

## Controls

- Move: wasd & cursor keys
- Plant Seed: Left Click 
- Crop: Right Click
- Zoom: Middle Click

## Staff

###  Programing

- tanitta (trit_techne) [Link](http://tanitta.net/)
- ray45422 [Link](https://twitter.com/ray45422)
- hoshi umeko

### Design & Modeling

- Zaslon [Link](http://starlightensign.com/)

### Sound

- OtObOx [Link](https://soundcloud.com/user7999881/)

**Comment by Zaslon** [comment]
"Over there"

## Description

In thew world everything has collapsed, the only thing we can trust is OIL!
Take it from bandits and survive for as long as possible.

## Controls

 - Move: WASD, QE
 - Zoom: Wheel
 - Camera move: Right drag
 - Shot: Space
 - Aim: Automatic

## Staff

###  Programing

- tanitta (trit_techne) [Link](http://tanitta.net/)
- ray45422 [Link](https://twitter.com/ray45422)
- hoshi umeko

### 2D & 3D Design

 - Hydrazin [Link](https://twitter.com/1_1udmh)

### Modeling

- Zaslon [Link](http://zaslon.info/)

### Sound

- OtObOx [Link](https://soundcloud.com/user7999881/)
