### ISSUE TITLE
敵を倒したらFuelTankItemをドロップするようにする

### ISSUE THREAD

**Issue by tanitta** [ld44-team-mukade/ld44-maingame#112]
EnemyShipにくっつけるComponentを作ることで実現できます
- 名前はFuelDrop Componentが良いと思います
- ドロップするFuelTankItemのPrefabをInspectorに指定できるようにしてください
- FuelTank ComponentをInspectorで指定できるようにしてください
- 指定されたFuelTank ComponentのRemainingが0以下になったらFuelTankItemを一つ，shipの周りにInstanceとして配置してください．
- 配置したInstanceのparentはnullに指定してください

**Comment by OtObOx** [comment]
ドロップすることを確認しました。
