### ISSUE TITLE
敵の死亡がわかりにくい

### ISSUE THREAD

**Issue by Zaslon** [ld44-team-mukade/ld44-maingame#159]
死んだ敵の表現がわかりにくい

**Comment by tanitta** [comment]
エフェクト入ってロックオンしなくなったのでかなりわかりやすくなったとおもわれです:+1:
あとは死んだ敵のライト消せばもっとわかりやすそう？？？

**Comment by OtObOx** [comment]
敵を倒した際に白いエフェクトが表示され敵を足したことがわかりやすくなったためイシューを閉じさせていただきます。
