### ISSUE TITLE
タイトル画面

### ISSUE THREAD

**Issue by tanitta** [ld44-team-mukade/ld44-maingame#17]
- [x] タイトル画面で何かをクリックしたときにゲーム中への遷移するようにする @HoshiUmeko 
- [ ] タイトルの文字の作成 @Hydraz1ne 
- [ ] Sceneのセットアップ @HoshiUmeko 
  - 3Dモデルを追加したり見栄えをいい感じにする
  - タイトル文字の入れ込み

**Comment by HoshiUmeko** [comment]
ボタンのデザイン雑なのでもうちょいこだわりたい
