### ISSUE TITLE
砲弾のPrefab

### ISSUE THREAD

**Issue by tanitta** [ld44-team-mukade/ld44-maingame#21]
`Assets\Project\Prefabs\StandardBullet`に雛形がある

- [x] スクリプト @HoshiUmeko 
  - 相手のShipにぶつかったらShipのFuelTank ComponentのDecrementFuelを呼び出してほしい．
  - LightComponentを仕込んで砲弾が飛んでいる間は発光させてほしい

- [x] 砲弾のデザイン @Hydraz1ne 
- [x] 砲弾のモデリング @Zaslon

**Comment by HoshiUmeko** [comment]
■問題点
BulletAttack
→Shipを複製した際のゲームオブジェクトの名前がShipじゃないとちゃんと処理できない
