### ISSUE TITLE
day night cycleが早い気がする

### ISSUE THREAD

**Issue by OtObOx** [ld44-team-mukade/ld44-maingame#210]
ちょーっとだけ早いかもしれない
気が付いたら真夜中ってふうに感じた

**Comment by OtObOx** [comment]
意見が欲しいです

**Comment by OtObOx** [comment]
#212　夕方が欲しいも含めて意見があれば

**Comment by tanitta** [comment]
確かにちょっと早いかもですね．時間が進む速度，半分くらいにしても良さそうです．

**Comment by tanitta** [comment]
@OtObOx MainGame Sceneの中のGameObjectの[Graphics]/Directional LightについているDayNightCycleというComponentのSpeedをInspectorで調整可能なのでとりあえずたたき台としていい感じの数値を設定してPR出してみてください～

**Comment by OtObOx** [comment]
ゆっくりになったのでとじる
