### ISSUE TITLE
夕方が欲しいなぁ

### ISSUE THREAD

**Issue by OtObOx** [ld44-team-mukade/ld44-maingame#212]
夕方がないので日が暮れたというより暗くなったという印象がある気がする

- [x] ライトの色の変更処理をDayNightCycleに実装する @tanitta 
- [ ] 必要であればInspectorで微調整を行う @OtObOx

**Comment by tanitta** [comment]
こちらで時間帯に応じてライトの色を変える（夕方はオレンジ）処理をDayNightCycle Componentにねじ込みますね～．
@OtObOx Inspectorでパラメータいじれるようにしておくのでいい感じに微調整してください✋

**Comment by OtObOx** [comment]
現状で問題ないのでとじます
