### ISSUE TITLE
船が砲弾以外に当たった場合に砲弾の着弾音が鳴ってる

### ISSUE THREAD

**Issue by HoshiUmeko** [ld44-team-mukade/ld44-maingame#223]
プレイヤーの船、敵の船問わず、船が砲弾以外の物体に当たった時も砲弾の着弾音が鳴ってます

**Comment by OtObOx** [comment]
現状船のコリジョンに入ると音が鳴る設定になってるので敵の弾が自分の船のコリジョンに当たるとなるようにすれば解決する…
wwise側で何とかなるとは思ってるけど要調査

**Comment by OtObOx** [comment]
プレイヤーとプレイヤーの砲弾同士のコリジョン判定はない敵も同じく（たにった談）
→発射時にコリジョン判定は起こらない
→着弾時のみdamageが再生されるようになるはず

**Comment by HoshiUmeko** [comment]
山とかの地形に当たった時とかも鳴ってました

プレイヤーを山に衝突させるとわかりやすいかもです

**Comment by OtObOx** [comment]
#238

**Comment by OtObOx** [comment]
修正したので閉じます
