### ISSUE TITLE
自機の弾の速度を速くする

### ISSUE THREAD

**Issue by HoshiUmeko** [ld44-team-mukade/ld44-maingame#226]
遠くから打っても敵に当たるレベルが良い
自機の速度と合算されるようにする

**Comment by tanitta** [comment]
とりあえず弾の速度を二倍にしたんですが，自機の速度と合算されるようにすると全く弾が当たらなくなるのでやってません．こちらは実装する際にFCSの強化も同時に行う必要がありそうです．

**Comment by tanitta** [comment]
自機の速度を加算するやつはちょっとデカそうなタスクなので #247 を新しく建てました．なのでこちらのissueはcloseします．
