### ISSUE TITLE
敵に砲弾が着弾した際にプレイヤー機にもダメージが入るようにする

### ISSUE THREAD

**Issue by tanitta** [ld44-team-mukade/ld44-maingame#227]
弾が敵に着弾したらPhysics.OverlapSphereで近くにいるShipに対してダメージを与える実装が楽かなーとか思いました．距離でダメージが減衰したらいいですね

**Comment by HoshiUmeko** [comment]
Consoleから爆風ダメージ見れるようになってます

**Comment by tanitta** [comment]
調整は自分がやってみます 👌

**Comment by tanitta** [comment]
dekita close simasu.
