### ISSUE TITLE
アイテムゲットしてなくてもアイテムゲットのSEが鳴る

### ISSUE THREAD

**Issue by HoshiUmeko** [ld44-team-mukade/ld44-maingame#256]
アイテムをゲットせずにアイテムを消滅させた場合もアイテムゲットのSEがなってます
一応おとぼさんアサインします

**Comment by OtObOx** [comment]
アイテムが破棄されると音が鳴る仕組みだったので砲弾が当たった場合も同様になるのが原因でした

**Comment by OtObOx** [comment]
多分直ったと思うので閉じます
