### ISSUE TITLE
燃料タンクアイテム

### ISSUE THREAD

**Issue by tanitta** [ld44-team-mukade/ld44-maingame#43]
敵を倒したら出てくる燃料タンクアイテムです
プレイヤーはこのアイテムを回収することで燃料を補給します

- [x] デザイン @Hydraz1ne 
- [x] モデリング @Zaslon 
- [x] 実装
  - 上下にふわふわ動いていると良さそう
  - 弾と接触したら爆発するようにしてほしい
  - コリジョンを入れておいてほしい
    - 後からShipのFuelTankComponentで燃料タンクアイテムに接触した際に回収するようにする

**Comment by Hydraz1ne** [comment]
![タンク](https://user-images.githubusercontent.com/49834984/56866927-1ecdab80-6a1a-11e9-9a1a-95c2f2010340.png)
