### ISSUE TITLE
MainGameからGameOverのシーン遷移

### ISSUE THREAD

**Issue by tanitta** [ld44-team-mukade/ld44-maingame#45]
Playerが破壊されると`Assets/Project/Scenes/MainGame/GameManager.cs`のメンバ関数`GoToGameOver`が呼ばれるので，その中身をいい感じに書き換えてGameOverSceneに切り替わるようにしてほしいです．

**Comment by OtObOx** [comment]
MainGameからGameOverへ遷移することを確認しましたのでクローズします。
