### ISSUE TITLE
主人公船

### ISSUE THREAD

**Issue by OtObOx** [ld44-team-mukade/ld44-maingame#5]
- [ ] 原画
- [ ] 3Dモデル
  - コリジョン
  - 表示モデル

**Comment by Hydraz1ne** [comment]
![sund](https://user-images.githubusercontent.com/49834984/56845656-8511db80-68ff-11e9-925f-1a68544ab053.png)

**Comment by Hydraz1ne** [comment]
![sund2](https://user-images.githubusercontent.com/49834984/56846120-d3c27400-6905-11e9-9f69-3189830525b5.png)

**Comment by Hydraz1ne** [comment]
![sund2mat](https://user-images.githubusercontent.com/49834984/56846320-e12d2d80-6908-11e9-999a-2c1875412771.png)

**Comment by Hydraz1ne** [comment]
![Geoff-Hunt-H M S -Victory-1](https://user-images.githubusercontent.com/49834984/56847844-0d05de80-691c-11e9-8414-f468b164e90d.jpg)

**Comment by Hydraz1ne** [comment]
![n10](https://user-images.githubusercontent.com/49834984/56847846-142cec80-691c-11e9-8344-b9248122cb4b.jpg)
