### ISSUE TITLE
タイトル画面のUIデザイン

### ISSUE THREAD

**Issue by OtObOx** [ld44-team-mukade/ld44-maingame#61]
- [x] 2D原案
- [x] 3Dモデル

**Comment by Hydraz1ne** [comment]
![Title](https://user-images.githubusercontent.com/49834984/56874464-00e16480-6a75-11e9-88e6-629dc89b4ac3.png)

**Comment by Hydraz1ne** [comment]
![タイトル](https://user-images.githubusercontent.com/49834984/56929251-122d7e00-6b14-11e9-9fad-010a030a8254.png)
タイトルロゴ

**Comment by Hydraz1ne** [comment]
![タイトル](https://user-images.githubusercontent.com/49834984/56929474-a39cf000-6b14-11e9-83d0-114f10fd1c0d.png)
タイトル

**Comment by Hydraz1ne** [comment]
![タイトル](https://user-images.githubusercontent.com/49834984/56929585-fc6c8880-6b14-11e9-9273-664e19f85733.png)
タイトル

**Comment by Hydraz1ne** [comment]
![START](https://user-images.githubusercontent.com/49834984/56929605-0abaa480-6b15-11e9-95bf-425684f5e1f8.png)
スタート

**Comment by OtObOx** [comment]
game overからexitを持ってくる（必要ならば）
#63 ゲームオーバー画面のUIデザイン
