### ISSUE TITLE
メインゲーム画面のUIデザイン

### ISSUE THREAD

**Issue by OtObOx** [ld44-team-mukade/ld44-maingame#62]
- [x] 2D原案
- [ ] 3Dモデル

**Comment by OtObOx** [comment]
#64 レバー（層確認用UI）をどのように入れるか

**Comment by Hydraz1ne** [comment]
![UI案](https://user-images.githubusercontent.com/49834984/56874324-2c178400-6a74-11e9-8109-ec5da7572871.png)

**Comment by Hydraz1ne** [comment]
![UI2](https://user-images.githubusercontent.com/49834984/56874340-4e110680-6a74-11e9-9530-91e4b1d745a0.png)

**Comment by Hydraz1ne** [comment]
![UI スコア](https://user-images.githubusercontent.com/49834984/56927639-a8ab7080-6b0f-11e9-8dc0-8783f13a046a.png)
スコアボード

**Comment by OtObOx** [comment]
計器類、照準、階層表示実装完了したので閉じます。
