### ISSUE TITLE
ゲームオーバー画面のUIデザイン

### ISSUE THREAD

**Issue by OtObOx** [ld44-team-mukade/ld44-maingame#63]
- [x] 2D原案
- [ ] 3Dモデル
- [x] スコアの表示 @HoshiUmeko

**Comment by Hydraz1ne** [comment]
![がめおべ画面](https://user-images.githubusercontent.com/49834984/56916422-cec31780-6af3-11e9-8deb-634159484cd8.png)

**Comment by Hydraz1ne** [comment]
![がめおべ画面2](https://user-images.githubusercontent.com/49834984/56916636-53159a80-6af4-11e9-9ad8-e81d8975bf99.png)

**Comment by tanitta** [comment]
#100 が終わったのでスコアを表示してください．ScoreBoard.scoreで取得できます．

**Comment by Hydraz1ne** [comment]
![GAME OVER](https://user-images.githubusercontent.com/49834984/56924444-e1474c00-6b07-11e9-8201-6f9b4b1cc949.png)
GAMEOVER

**Comment by Hydraz1ne** [comment]
![EXIT](https://user-images.githubusercontent.com/49834984/56924467-ed330e00-6b07-11e9-9026-7312054bf8a7.png)
EXIT

**Comment by Hydraz1ne** [comment]
![Restart](https://user-images.githubusercontent.com/49834984/56924496-fe7c1a80-6b07-11e9-8080-1320916c9359.png)
RESTART

**Comment by OtObOx** [comment]
全て実装したので閉じます。
