### ISSUE TITLE
船のプロペラを回す

### ISSUE THREAD

**Issue by tanitta** [ld44-team-mukade/ld44-maingame#70]
- [ ] プロペラのgameobjectにComponentをつけてTransformを回転させる
- [ ] エンジン音を鳴らす

**Comment by OtObOx** [comment]
https://www.audiokinetic.com/en/courses/wwise301/?source=wwise301&id=Game_Parameters#read

**Comment by ray45422** [comment]
僕がやりまぁす

**Comment by OtObOx** [comment]
https://www.youtube.com/watch?v=Vg6YSezwp34&feature=youtu.be&t=40
wwiseと数字を共有する方法
