### ISSUE TITLE
今のフィールドの高さを表す，船を中心にした同心円状の表示

### ISSUE THREAD

**Issue by tanitta** [ld44-team-mukade/ld44-maingame#71]
船が微妙にふわふわするのでどの平面で動いているのが分かりづらいのを解決する．
メッシュで線を立体にして形状を作ってもらえるとHDRPの相性も良いと思う
Emissionのマテリアルを割り当てる予定
- [x] デザイン @Hydraz1ne 
- [x] モデリング @Zaslon 
- [x] シーンへの組み込み等 @tanitta

**Comment by tanitta** [comment]
![image](https://user-images.githubusercontent.com/1937287/56867138-cfd54580-6a1c-11e9-9450-1ce8847c5e01.png)

**Comment by Hydraz1ne** [comment]
![階層　UI](https://user-images.githubusercontent.com/49834984/56874276-d7740900-6a73-11e9-8a58-138e3616dd7c.png)
