### ISSUE TITLE
中立の船

### ISSUE THREAD

**Issue by OtObOx** [ld44-team-mukade/ld44-maingame#8]
- [ ] 原画モデル
- [ ] 3Dモデル

**Comment by Hydraz1ne** [comment]
![中立船](https://user-images.githubusercontent.com/49834984/56865123-53833800-6a05-11e9-8aeb-2aa56f9c80b3.png)

海賊船も同じ船体を使用する
主人公船の1.5～1.7倍くらいでオナシャス

**Comment by Zaslon** [comment]
(45 x 10 x 10) x 1.5~1.7

**Comment by Zaslon** [comment]
ライトは忘れた
